### ISSUE TITLE
roll_forward and roll_backward not working

### ISSUE THREAD

**Issue by srshkmr** [gocardless/business#46]
Version: 1.16.0
Ruby: 2.6.3p62
Rails: 5.0.1

The roll_forward and roll_backward methods are returning the current date instead of previous and next business day

```
 current_date = Date.today.in_time_zone('Australia/Melbourne')
      calendar = Business::Calendar.new(
        working_days: %w[mon tue wed thu fri],
        holidays: HolidayList.holidays(current_date)
      )

      p calendar
      p calendar.roll_forward(Time.now.in_time_zone('Australia/Melbourne').to_date)
```
Expected:

```
#<Business::Calendar:0x00007f8933f20d00 @extra_working_dates=[], @working_days=["mon", "tue", "wed", "thu", "fri"], @holidays=[Wed, 25 Dec 2019, Thu, 26 Dec 2019]>
Fri, 06 Dec 2019
```

Received:

```
#<Business::Calendar:0x00007f8933f20d00 @extra_working_dates=[], @working_days=["mon", "tue", "wed", "thu", "fri"], @holidays=[Wed, 25 Dec 2019, Thu, 26 Dec 2019]>
Thu, 05 Dec 2019
```

**Comment by Sannim1** [comment]
Hi @srshkmr 

I think this is expected behaviour. 

> The roll_forward and roll_backward methods snap a date to a nearby business day. If provided with a business day, they will return that date. Otherwise, they will advance (forward for roll_forward and backward for roll_backward) until a business day is found.

From the README in the section about [`Business Day Arithmetic`](https://github.com/gocardless/business#business-day-arithmetic) .

The behaviour you are describing is actually performed by the `next/previous_business_day` methods which can be found in https://github.com/gocardless/business/blob/155d9aad3daa870612c06be6316817faeb4c98a8/lib/business/calendar.rb#L79-L95

I hope that helps.

**Comment by srshkmr** [comment]
Thanks for that @Sannim1 , That really helped.
